### Create new comment
POST http://localhost:3335/api/comment/111 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2M2UzOTBiMThmODFjNWU3MDdiZTcyMzEiLCJlbWFpbCI6InRzZHNkdHlAZ21haWwuY29tIiwibmFtZSI6ImRkaGlwIEhhd2siLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE2NzYxMTMxMTgsImV4cCI6MTY3NjExOTExOH0.inlJKYwXximoRliX1SZdxLuiXT_YYB3g_8ZWpQ-7bJg

{
  "text": "guitaaaaaaaaaar",
  "positive": "new amazing exelent cool guitar. Nisi consectetur qui pariatur.",
  "negative": "Adipisicing dolore elit consequat culpa. Irure excepteur.",
  "grade": 1
}

### Find existed comments
GET http://localhost:3335/api/comment/1 HTTP/1.1
