### Create new order
POST http://localhost:3335/api/order HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2M2UzOTBiMThmODFjNWU3MDdiZTcyMzEiLCJlbWFpbCI6InRzZHNkdHlAZ21haWwuY29tIiwibmFtZSI6ImRkaGlwIEhhd2siLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE2NzYwMjYzMTAsImV4cCI6MTY3NjAzMjMxMH0.rBnO8eOC6NKqrJI-GaYpJd2qBp7KNfO6rfcCCh3GpJ8

{
  "products": [
    {
      "id": 1,
      "amount": 1
    },
    {
      "id": 2,
      "amount": 1
    }
  ]
}

### Find existed order
GET http://localhost:3335/api/order/20 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2M2UzOTBiMThmODFjNWU3MDdiZTcyMzEiLCJlbWFpbCI6InRzZHNkdHlAZ21haWwuY29tIiwibmFtZSI6ImRkaGlwIEhhd2siLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE2NzYxMTY3ODgsImV4cCI6MTY3NjEyMjc4OH0.BGveSkHHotI3NIsUM_IqqXr9CrsBiEzi5x7-sArkiVQ


### Find existed orders
GET http://localhost:3335/api/order?sortField=totalSum&page=1 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2M2UzOTBiMThmODFjNWU3MDdiZTcyMzEiLCJlbWFpbCI6InRzZHNkdHlAZ21haWwuY29tIiwibmFtZSI6ImRkaGlwIEhhd2siLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE2NzYxMjE2NTMsImV4cCI6MTY3NjEyNzY1M30.ncbTPKiEvF9pPEu2KZH0fzDBA_9HoC3Jvtfd_n2lAIw

### Delete order
DELETE http://localhost:3335/api/order/21 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2M2UzOTBiMThmODFjNWU3MDdiZTcyMzEiLCJlbWFpbCI6InRzZHNkdHlAZ21haWwuY29tIiwibmFtZSI6ImRkaGlwIEhhd2siLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE2NzYwMTE5MjcsImV4cCI6MTY3NjAxNzkyN30.O6NzMB59tYOnZbiJi2dppg1OYzFa21mikUBzsVwefo4
