### Create user
POST http://localhost:3333/api/auth/register HTTP/1.1
Content-Type: application/json

{
  "name": "ddhip Hawk",
  "email": "dsdty@gmail.com",
  "password": "123456"
}

### Login user
POST http://localhost:3333/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "tsdsdty@gmail.com",
  "password": "123456"
}


### Check user authorization
GET http://localhost:3333/api/auth/check-authorization HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2M2UzOTBiMThmODFjNWU3MDdiZTcyMzEiLCJlbWFpbCI6InRzZHNkdHlAZ21haWwuY29tIiwibmFtZSI6ImRkaGlwIEhhd2siLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE2NzYxMDgzMzgsImV4cCI6MTY3NjExNDMzOH0.R1W4ZaDKJQbNMSYeLCwLNU_LP-EwHBOlegkUfxXyqAU
